name: Release CI

on:
  workflow_dispatch:

jobs:


  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build arm64 docker
        run: docker build -t arm64 -f Dockerfile .
      - name: Compile arm64 build
        run: |
          docker run --rm \
            -v /opt/dist:/opt/dist \
            -e DIST_DIR='/opt/dist' \
            -e RELEASE_TAG="$GITHUB_REF_NAME" \
            -e NATIVE_ARCH="arm64" \
            -e ABI_ID=2 \
            -e ABI_TARGET="arm64-v8a" \
            arm64
      - name: Upload arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-build
          path: /opt/dist

  

  publish:
    runs-on: ubuntu-latest
    needs:
      - build-arm64
    permissions:
      contents: write
    steps:
      
      - name: Download arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: arm64-build
          path: dist
   
      - name: Set VERSION_CODE
        run: |
          ALL_VARIANTS=1
          VERSION_CODE=$(cat "$GITHUB_WORKSPACE/app/versionCode.txt")
          ((VERSION_CODE += ALL_VARIANTS))
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
          files: "dist/*.apk"
        #  body_path: ${{ github.workspace }}/metadata/en-US/changelogs/${{ env.VERSION_CODE }}.txt
